server:
  port: 90
spring:
  application:
    name: zzj
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/1702a?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 888888
  jackson:
    date-format: yyyy-MM-dd
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
mybatis:
  mapper-locations: classpath*:mapper/*.xml
